-- ============================================================
-- Migración manual: tabla `tarea` (Fase 2 de la jerarquía
--                   DUENO -> AGENTE -> ASISTENTE)
--                   (PostgreSQL / Supabase — PROD)
-- Fecha: 2026-06-11
--
-- Cambios:
--   - Nueva tabla `tarea`. Un AGENTE/DUENO le asigna tareas a su ASISTENTE.
--     objetivo NULL = tarea discreta (se marca a mano); objetivo con número =
--     cuota automática (leads distintos contactados por el asistente en el día).
--
-- Nombres reales verificados en el código (FKs):
--   * agente(id)        -> asignado_a_id, creado_por_id
--   * leads(id)         -> lead_id        (tabla "leads", no "lead": palabra reservada)
--   * inmobiliaria(id)  -> inmobiliaria_id
--
-- IMPORTANTE:
--   * HACER BACKUP EN SUPABASE ANTES DE EJECUTAR
--     (Dashboard > Database > Backups, o pg_dump).
--   * Ejecutar este script contra la base ANTES de deployar el backend con
--     los cambios (prod usa ddl-auto=validate y no levanta si falta la tabla).
--     El proyecto no usa Flyway ni Liquibase.
--   * Todo corre dentro de UNA transacción: si algo falla se revierte
--     completo y la base queda como estaba.
--   * Sin backfill: tabla nueva.
-- ============================================================

BEGIN;

CREATE TABLE tarea (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR(200) NOT NULL,
    asignado_a_id    BIGINT NOT NULL REFERENCES agente(id),
    creado_por_id    BIGINT NOT NULL REFERENCES agente(id),
    lead_id          BIGINT NULL     REFERENCES leads(id),
    inmobiliaria_id  BIGINT NOT NULL REFERENCES inmobiliaria(id),
    objetivo         INT NULL,
    completada       BOOLEAN NOT NULL DEFAULT false,
    fecha_completada TIMESTAMP NULL,
    fecha_objetivo   TIMESTAMP NOT NULL,
    fecha_creacion   TIMESTAMP NOT NULL
);

-- Índices para las consultas del service:
--   - vista del asistente: tareas de hoy por asignado.
CREATE INDEX idx_tarea_asignado_fecha ON tarea (asignado_a_id, fecha_objetivo);
--   - vista del supervisor: tareas que le creó a un asistente.
CREATE INDEX idx_tarea_creado_asignado ON tarea (creado_por_id, asignado_a_id);
--   - validación cross-tenant por inmobiliaria.
CREATE INDEX idx_tarea_inmobiliaria ON tarea (inmobiliaria_id);

COMMIT;

-- ============================================================
-- VERIFICACIÓN (correr después del COMMIT):
--
-- La tabla debe existir con sus 11 columnas:
--   SELECT column_name, data_type, is_nullable
--   FROM information_schema.columns
--   WHERE table_name = 'tarea'
--   ORDER BY ordinal_position;
--
-- Deben figurar las 4 FKs (asignado_a_id, creado_por_id, lead_id, inmobiliaria_id):
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint
--   WHERE conrelid = 'tarea'::regclass AND contype = 'f';
--
-- Deben figurar los 3 índices creados arriba:
--   SELECT indexname FROM pg_indexes WHERE tablename = 'tarea';
-- ============================================================
