-- ============================================================
-- Migración manual: multi-tenant por Inmobiliaria (PostgreSQL / Supabase — PROD)
-- Fecha: 2026-06-09
--
-- Cambios:
--   - Nueva tabla `inmobiliaria`.
--   - Nuevas columnas en `agente`: inmobiliaria_id, rol,
--     debe_cambiar_password, activo.
--   - Backfill: cada agente existente queda como DUENO de su
--     propia inmobiliaria recién creada. Funciona con N agentes.
--
-- NO se toca ninguna otra tabla (leads, interaccion, propiedad,
-- operacion, busqueda, evento_operacion, foto_propiedad).
-- La inmobiliaria de un lead se deriva por join lead -> agente -> inmobiliaria.
--
-- IMPORTANTE:
--   * HACER BACKUP EN SUPABASE ANTES DE EJECUTAR
--     (Dashboard > Database > Backups, o pg_dump).
--   * Ejecutar este script contra la base ANTES de deployar el
--     backend con los cambios (prod usa ddl-auto=validate y no
--     levanta si faltan las columnas). El proyecto no usa
--     Flyway ni Liquibase.
--   * Todo corre dentro de UNA transacción: si algo falla,
--     se revierte completo y la base queda como estaba.
-- ============================================================

BEGIN;

-- 1) Tabla inmobiliaria.
--    fecha_creacion es TIMESTAMP sin zona: el backend guarda LocalDateTime
--    en hora argentina (ZONA_ARGENTINA), acá replicamos ese criterio.
CREATE TABLE inmobiliaria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    fecha_creacion  TIMESTAMP
);

-- 2) Nuevas columnas en agente, primero NULLables para poder backfillear.
ALTER TABLE agente ADD COLUMN inmobiliaria_id BIGINT NULL;
ALTER TABLE agente ADD COLUMN rol VARCHAR(20) NULL;
ALTER TABLE agente ADD COLUMN debe_cambiar_password BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE agente ADD COLUMN activo BOOLEAN NOT NULL DEFAULT true;

-- 3) Backfill: una inmobiliaria por agente existente, agente como DUENO.
--    Loop por agente (no asume que haya uno solo) usando RETURNING para
--    capturar el id recién insertado.
DO $$
DECLARE
    fila_agente RECORD;
    nueva_inmobiliaria_id BIGINT;
BEGIN
    FOR fila_agente IN
        SELECT id, nombre, apellido FROM agente WHERE inmobiliaria_id IS NULL
    LOOP
        INSERT INTO inmobiliaria (nombre, fecha_creacion)
        VALUES (
            'Inmobiliaria de '
                || COALESCE(fila_agente.nombre, '')
                || ' '
                || COALESCE(fila_agente.apellido, ''),
            now() AT TIME ZONE 'America/Argentina/Buenos_Aires'
        )
        RETURNING id INTO nueva_inmobiliaria_id;

        UPDATE agente
        SET inmobiliaria_id = nueva_inmobiliaria_id,
            rol = 'DUENO'
        WHERE id = fila_agente.id;
    END LOOP;
END $$;

-- 4) Con el backfill hecho, endurecer las columnas y agregar la FK.
ALTER TABLE agente ALTER COLUMN inmobiliaria_id SET NOT NULL;
ALTER TABLE agente ALTER COLUMN rol SET NOT NULL;
ALTER TABLE agente
    ADD CONSTRAINT fk_agente_inmobiliaria
    FOREIGN KEY (inmobiliaria_id) REFERENCES inmobiliaria(id);

-- 5) Índice para las queries por tenant (matching, equipo, stats).
CREATE INDEX idx_agente_inmobiliaria ON agente (inmobiliaria_id);

COMMIT;

-- ============================================================
-- VERIFICACIÓN (correr después del COMMIT):
--
-- Debe dar 0:
--   SELECT count(*) FROM agente WHERE inmobiliaria_id IS NULL;
--
-- Debe dar 0:
--   SELECT count(*) FROM agente WHERE rol IS NULL;
--
-- Control agente <-> inmobiliaria (cada agente con su inmobiliaria y rol DUENO):
--   SELECT a.id, a.nombre, a.apellido, a.email, a.rol, a.activo,
--          i.id AS inmobiliaria_id, i.nombre AS inmobiliaria
--   FROM agente a
--   JOIN inmobiliaria i ON i.id = a.inmobiliaria_id
--   ORDER BY a.id;
--
-- Debe coincidir la cantidad de inmobiliarias con la de agentes pre-migración:
--   SELECT count(*) FROM inmobiliaria;
-- ============================================================
